# Generated by Django 5.0 on 2024-01-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VEG_REC', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
