# Generated by Django 5.0 on 2024-01-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEG_REC', '0002_rename_receipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Rimage',
            field=models.ImageField(upload_to='RecipeImages'),
        ),
    ]
