# Generated by Django 5.0 on 2024-01-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to=None)),
            ],
        ),
    ]
