# Generated by Django 5.0 on 2024-01-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
